package pojos;
// Generated 03-dic-2023 22:45:55 by Hibernate Tools 4.3.1

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {
    
    //Atributos
     private String nombre;
     private Integer titulares;
     private Integer suplentes;
     private String directorTecnico;
     private Integer puntos;
     private Integer partidosJugados;

    
    //Getters y Setters
    public String getNombre() {
        return this.nombre;
    }    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public Integer getTitulares() {
        return this.titulares;
    }    
    public void setTitulares(Integer titulares) {
        this.titulares = titulares;
    }
    
    public Integer getSuplentes() {
        return this.suplentes;
    }    
    public void setSuplentes(Integer suplentes) {
        this.suplentes = suplentes;
    }
    
    public String getDirectorTecnico() {
        return this.directorTecnico;
    }    
    public void setDirectorTecnico(String directorTecnico) {
        this.directorTecnico = directorTecnico;
    }
    
    public Integer getPuntos() {
        return this.puntos;
    }    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    
    public Integer getPartidosJugados() {
        return this.partidosJugados;
    }    
    public void setPartidosJugados(Integer partidosJugados) {
        this.partidosJugados = partidosJugados;
    }
    
    //Constructores
    public Equipo() {
    }
	
    public Equipo(String nombre) {
        this.nombre = nombre;
    }
    
    public Equipo(String nombre, Integer titulares, Integer suplentes, String directorTecnico, Integer puntos, Integer partidosJugados) {
       this.nombre = nombre;
       this.titulares = titulares;
       this.suplentes = suplentes;
       this.directorTecnico = directorTecnico;
       this.puntos = puntos;
       this.partidosJugados = partidosJugados;
    }




}


